[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
# remappings here are used to resolve imports in the contracts. 
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options